# Node App 1 ----------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-miner
spec:
  replicas: 5
  selector:
    matchLabels:
      app: py-miner
  template:
    metadata:
      labels:
        app: py-miner
    spec:
      containers:
        - name: py-miner
          image: wynd-py-miner:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: py-miner-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: py-miner
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: py-miner-service
spec:
  type: LoadBalancer
  selector:
    app: py-miner
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
